### ISSUE TITLE
Transaction is expired

### ISSUE THREAD

**Issue by arthas207** [phantasma-io/phantasma-ts#21]
Hello,
       I encountered an error like this:'CheckTx returned code 2 Transaction is expired  7e818cec09ba98ab4888de13d995307bdfd3261c86493e28e7634b15d9023a1b  9909343' when I used the demo which is called 'Building a Transaction' in the README.md.And I tried to set the expired field very large,but it didn't work. Isn't this sdk a newest version?

**Comment by TeknoPT** [comment]
Thanks for submitting the issue, it's fixed, it was sending the data wrong to the endpoint
